title: h.ayhx # name of the site
author: Chee Meng Au Yong # name of site's author
email: auyongcheemeng@gmail.com # email of site's author
url: https://h.auyong.me # root address of the site
#url: https://testflight.auyong.me # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  A tiny Pi server on the edge of the internet. 
  Usually serves the hot cup of tea or milo and on rare ocassions: HTTPS page requests. 

permalink: /:slug.html

favicon: "favicon.ico" # name+extension of favicon (which must be put on the root folder)
goat_counter: "ayhx" # put your GoatCounter name if you want to use GoatCounter analytics

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

permalink: /:categories/:year/:month/:day/:title:output_ext

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

kramdown:
  smart_quotes: apos,apos,quot,quot
  typographic_symbols: {hellip: ...}

feed:
  posts_limit: 10

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - .wellknown
exclude: 
  - Gemfile
  - "*.gemspec"

defaults:
  -
    scope:
      path: "pdf/**/*.pdf"
    values:
      sitemap: false
  -
    scope:
      path: "files/*"
    values:
      sitemap: false
